### ISSUE TITLE
handle bad network connections and down states

### ISSUE THREAD

**Issue by eastein** [eastein/thingsbus#3]
This happens now if packet loss is really bad during `service_discovery.ServiceFinder._get_broker_url`:

```
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "thingsbus/client.py", line 44, in run
    conn = zmqsub.ConnectSub(self.broker_url)
  File "/home/eastein/venvs/thingsbus/local/lib/python2.7/site-packages/zmqfan/zmqsub.py", line 27, in __init__
    self.s.connect(url)
  File "zmq/backend/cython/socket.pyx", line 471, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4298)
ZMQError: Invalid argument
```

If there's no connection at all during service_discovery, this happens:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eastein/venvs/thingsbus/local/lib/python2.7/site-packages/dns/resolver.py", line 824, in query
    raise NoNameservers
dns.resolver.NoNameservers
```

**Comment by eastein** [comment]
Right now, if we establish everything fine to start & then fail later, the adaptor and the client will both silently fail.

https://github.com/eastein/zmqfan/issues/4 is the issue I've opened for dealing with this within zmqfan. We will want to abstract it into something basic.

**Comment by eastein** [comment]
It's tempting to add various broker configuration info to the 'firehose' socket, including:

* `DIRECTORY_INTERVAL`
* `DIRECTORY_EXPIRE`
* `INPUT_PORT`
* `DIRECTORY_PORT`
